import { db } from "@/app/_lib/prisma";
import { AccountType, BalanceType } from "@prisma/client";

const defaultAccounts = [
  {
    name: "ATIVO",
    code: "1",
    type: "ASSET",
    balanceType: "DEBIT",
    isAnalytical: false,
  },
  {
    name: "ATIVO CIRCULANTE",
    code: "1.1",
    type: "ASSET",
    balanceType: "DEBIT",
    parentCode: "1",
    isAnalytical: false,
  },
  {
    name: "CAIXA E EQUIVALENTE DE CAIXA",
    code: "1.1.1",
    type: "ASSET",
    balanceType: "DEBIT",
    parentCode: "1.1",
    isAnalytical: false,
  },

  {
    name: "CONTAS A RECEBER - CURTO PRAZO",
    code: "1.1.2",
    type: "ASSET",
    balanceType: "DEBIT",
    parentCode: "1.1",
    isAnalytical: true,
  },
  {
    name: "ADIANTAMENTO A FORNECEDOR",
    code: "1.1.3",
    type: "ASSET",
    balanceType: "DEBIT",
    parentCode: "1.1",
    isAnalytical: true,
  },
  {
    name: "ESTOQUE",
    code: "1.1.4",
    type: "ASSET",
    balanceType: "DEBIT",
    parentCode: "1.1",
    isAnalytical: true,
  },
  {
    name: "DESPESAS ANTECIPADAS",
    code: "1.1.5",
    type: "ASSET",
    balanceType: "DEBIT",
    parentCode: "1.1",
    isAnalytical: true,
  },
  {
    name: "ATIVO NAO CIRCULANTE",
    code: "1.2",
    type: "ASSET",
    balanceType: "DEBIT",
    parentCode: "1",
    isAnalytical: false,
  },
  {
    name: "IMOBILIZADO",
    code: "1.2.1",
    type: "ASSET",
    balanceType: "DEBIT",
    parentCode: "1.2",
    isAnalytical: false,
  },
  {
    name: "EQUIPAMENTOS E FERRAMENTAS",
    code: "1.2.1.1",
    type: "ASSET",
    balanceType: "DEBIT",
    parentCode: "1.2.1",
    isAnalytical: true,
  },
  {
    name: "MOVEIS E UTENSILIOS",
    code: "1.2.1.2",
    type: "ASSET",
    balanceType: "DEBIT",
    parentCode: "1.2.1",
    isAnalytical: true,
  },
  {
    name: "EQUIPAMENTOS DE INFORMATICA",
    code: "1.2.1.3",
    type: "ASSET",
    balanceType: "DEBIT",
    parentCode: "1.2.1",
    isAnalytical: true,
  },
  {
    name: "VEICULOS",
    code: "1.2.1.4",
    type: "ASSET",
    balanceType: "DEBIT",
    parentCode: "1.2.1",
    isAnalytical: true,
  },
  {
    name: "INSTALACOES",
    code: "1.2.1.5",
    type: "ASSET",
    balanceType: "DEBIT",
    parentCode: "1.2.1",
    isAnalytical: true,
  },
  {
    name: "SISTEMAS E SOFTWARES",
    code: "1.2.1.6",
    type: "ASSET",
    balanceType: "DEBIT",
    parentCode: "1.2.1",
    isAnalytical: true,
  },
  {
    name: "EQUIPAMENTOS DE SEGURANCA",
    code: "1.2.1.7",
    type: "ASSET",
    balanceType: "DEBIT",
    parentCode: "1.2.1",
    isAnalytical: true,
  },
  {
    name: "MAQUINAS E EQUIPAMENTOS DE APOIO",
    code: "1.2.1.8",
    type: "ASSET",
    balanceType: "DEBIT",
    parentCode: "1.2.1",
    isAnalytical: true,
  },
  {
    name: "CONTAS A RECEBER - LONGO PRAZO",
    code: "1.2.2",
    type: "ASSET",
    balanceType: "DEBIT",
    parentCode: "1.2",
    isAnalytical: true,
  },
  {
    name: "PASSIVO",
    code: "2",
    type: "LIABILITY",
    balanceType: "CREDIT",
    isAnalytical: false,
  },
  {
    name: "PASSIVO CIRCULANTE",
    code: "2.1",
    type: "LIABILITY",
    balanceType: "CREDIT",
    parentCode: "2",
    isAnalytical: false,
  },
  {
    name: "CONTAS A PAGAR - CURTO PRAZO",
    code: "2.1.1",
    type: "LIABILITY",
    balanceType: "CREDIT",
    parentCode: "2.1",
    isAnalytical: true,
  },
  {
    name: "SALARIOS E ENCARGOS",
    code: "2.1.2",
    type: "LIABILITY",
    balanceType: "CREDIT",
    parentCode: "2.1",
    isAnalytical: false,
  },
  {
    name: "SALARIOS A PAGAR",
    code: "2.1.2.1",
    type: "LIABILITY",
    balanceType: "CREDIT",
    parentCode: "2.1.2",
    isAnalytical: true,
  },
  {
    name: "FERIAS A PAGAR",
    code: "2.1.2.2",
    type: "LIABILITY",
    balanceType: "CREDIT",
    parentCode: "2.1.2",
    isAnalytical: true,
  },
  {
    name: "13 A PAGAR",
    code: "2.1.2.3",
    type: "LIABILITY",
    balanceType: "CREDIT",
    parentCode: "2.1.2",
    isAnalytical: true,
  },
  {
    name: "INSS A RECOLHER",
    code: "2.1.2.4",
    type: "LIABILITY",
    balanceType: "CREDIT",
    parentCode: "2.1.2",
    isAnalytical: true,
  },
  {
    name: "FGTS A RECOLHER",
    code: "2.1.2.5",
    type: "LIABILITY",
    balanceType: "CREDIT",
    parentCode: "2.1.2",
    isAnalytical: true,
  },
  {
    name: "IRRF SOBRE SALARIO A RECOLHER",
    code: "2.1.2.6",
    type: "LIABILITY",
    balanceType: "CREDIT",
    parentCode: "2.1.2",
    isAnalytical: true,
  },
  {
    name: "CONTRIBUICOES SINDICAIS A RECOLHER",
    code: "2.1.2.7",
    type: "LIABILITY",
    balanceType: "CREDIT",
    parentCode: "2.1.2",
    isAnalytical: true,
  },
  {
    name: "OUTRAS OBRIGACOES TRABALHISTAS",
    code: "2.1.2.8",
    type: "LIABILITY",
    balanceType: "CREDIT",
    parentCode: "2.1.2",
    isAnalytical: true,
  },
  {
    name: "VALORES A REPASSAR",
    code: "2.1.3",
    type: "LIABILITY",
    balanceType: "CREDIT",
    parentCode: "2.1",
    isAnalytical: false,
  },
  {
    name: "VALORES A REPASSAR A TERCEIROS",
    code: "2.1.3.1",
    type: "LIABILITY",
    balanceType: "CREDIT",
    parentCode: "2.1.3",
    isAnalytical: true,
  },
  {
    name: "COMISSOE A PAGAR",
    code: "2.1.4",
    type: "LIABILITY",
    balanceType: "CREDIT",
    parentCode: "2.1",
    isAnalytical: true,
  },
  {
    name: "RECEITA DIFERIDA",
    code: "2.1.5",
    type: "LIABILITY",
    balanceType: "CREDIT",
    parentCode: "2.1",
    isAnalytical: true,
  },
  {
    name: "ADIANTAMENTO DE CLIENTES",
    code: "2.1.6",
    type: "LIABILITY",
    balanceType: "CREDIT",
    parentCode: "2.1",
    isAnalytical: true,
  },
  {
    name: "EMPRESTIMOS E FINANCIAMENTOS - CURTO PRAZO",
    code: "2.1.7",
    type: "LIABILITY",
    balanceType: "CREDIT",
    parentCode: "2.1",
    isAnalytical: true,
  },
  {
    name: "PASSIVO NAO CIRCULANTE",
    code: "2.2",
    type: "LIABILITY",
    balanceType: "CREDIT",
    parentCode: "2",
    isAnalytical: false,
  },
  {
    name: "CONTAS A PAGAR - LONGO PRAZO",
    code: "2.2.1",
    type: "LIABILITY",
    balanceType: "CREDIT",
    parentCode: "2.2",
    isAnalytical: true,
  },
  {
    name: "EMPRESTIMOS E FINANCIAMENTOS - LONGO PRAZO",
    code: "2.2.2",
    type: "LIABILITY",
    balanceType: "CREDIT",
    parentCode: "2.2",
    isAnalytical: true,
  },
  {
    name: "PATRIMONIO LIQUIDO",
    code: "3",
    type: "EQUITY",
    balanceType: "CREDIT",
    isAnalytical: false,
  },
  {
    name: "CAPITAL SOCIAL",
    code: "3.1",
    type: "EQUITY",
    balanceType: "CREDIT",
    parentCode: "3",
    isAnalytical: true,
  },
  {
    name: "LUCRO (PREJUIZO) ACUMULADO",
    code: "3.2",
    type: "EQUITY",
    balanceType: "BOTH",
    parentCode: "3",
    isAnalytical: true,
  },
  {
    name: "RECEITA",
    code: "4",
    type: "REVENUE",
    balanceType: "CREDIT",
    isAnalytical: false,
  },
  {
    name: "RECEITA DE VENDAS",
    code: "4.1",
    type: "REVENUE",
    balanceType: "CREDIT",
    parentCode: "4",
    isAnalytical: true,
  },
  {
    name: "RECEITA DE ASSISTENCIA TECNICA",
    code: "4.2",
    type: "REVENUE",
    balanceType: "CREDIT",
    parentCode: "4",
    isAnalytical: true,
  },
  {
    name: "RECEITA DE INTERMEDIACAO",
    code: "4.3",
    type: "REVENUE",
    balanceType: "CREDIT",
    parentCode: "4",
    isAnalytical: true,
  },
  {
    name: "RECEITA FINANCEIRA",
    code: "4.4",
    type: "REVENUE",
    balanceType: "CREDIT",
    parentCode: "4",
    isAnalytical: false,
  },
  {
    name: "JUROS RECEBIDOS DE APLICACOES",
    code: "4.4.1",
    type: "REVENUE",
    balanceType: "CREDIT",
    parentCode: "4.4",
    isAnalytical: true,
  },
  {
    name: "DESCONTOS FINANCEIROS OBTIDOS",
    code: "4.4.2",
    type: "REVENUE",
    balanceType: "CREDIT",
    parentCode: "4.4",
    isAnalytical: true,
  },
  {
    name: "OUTRAS RECEITAS",
    code: "4.5",
    type: "REVENUE",
    balanceType: "CREDIT",
    parentCode: "4",
    isAnalytical: false,
  },
  {
    name: "CASHBACK",
    code: "4.5.1",
    type: "REVENUE",
    balanceType: "CREDIT",
    parentCode: "4.5",
    isAnalytical: true,
  },
  {
    name: "REEMBOLSO",
    code: "4.5.2",
    type: "REVENUE",
    balanceType: "CREDIT",
    parentCode: "4.5",
    isAnalytical: true,
  },
  {
    name: "DESPESAS",
    code: "5",
    type: "EXPENSE",
    balanceType: "DEBIT",
    isAnalytical: false,
  },
  {
    name: "DEPESAS ADMINISTRATIVAS",
    code: "5.1",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5",
    isAnalytical: false,
  },
  {
    name: "ALUGUEL",
    code: "5.1.1",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.1",
    isAnalytical: true,
  },
  {
    name: "PLANO DE CELULAR",
    code: "5.1.2",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.1",
    isAnalytical: true,
  },
  {
    name: "DOMINIO",
    code: "5.1.3",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.1",
    isAnalytical: true,
  },
  {
    name: "HOSPEDAGEM",
    code: "5.1.4",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.1",
    isAnalytical: true,
  },
  {
    name: "CERTIFICADO DIGITAL",
    code: "5.1.5",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.1",
    isAnalytical: true,
  },
  {
    name: "CONTABILIDADE",
    code: "5.1.6",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.1",
    isAnalytical: true,
  },
  {
    name: "MATERIAL DE USO E CONSUMO",
    code: "5.1.7",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.1",
    isAnalytical: true,
  },
  {
    name: "ESTACIONAMENTO",
    code: "5.1.8",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.1",
    isAnalytical: true,
  },
  {
    name: "REGISTRO DE MARCA",
    code: "5.1.9",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.1",
    isAnalytical: true,
  },
  {
    name: "DISTRIBUICAO DE LUCROS",
    code: "5.1.10",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.1",
    isAnalytical: true,
  },
  {
    name: "DESPESAS COM VENDAS",
    code: "5.2",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5",
    isAnalytical: false,
  },
  {
    name: "COMISSAO",
    code: "5.2.1",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.2",
    isAnalytical: true,
  },
  {
    name: "FRETE",
    code: "5.2.2",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.2",
    isAnalytical: true,
  },
  {
    name: "BRINDES",
    code: "5.2.3",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.2",
    isAnalytical: true,
  },
  {
    name: "DESPESAS COM MARKETING",
    code: "5.3",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5",
    isAnalytical: false,
  },
  {
    name: "CAMISAS",
    code: "5.3.1",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.3",
    isAnalytical: true,
  },
  {
    name: "TRAFEGO PAGO",
    code: "5.3.2",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.3",
    isAnalytical: true,
  },
  {
    name: "DESIGNER",
    code: "5.3.3",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.3",
    isAnalytical: true,
  },
  {
    name: "CONTEUDO",
    code: "5.3.4",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.3",
    isAnalytical: true,
  },
  {
    name: "STICKERS",
    code: "5.3.5",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.3",
    isAnalytical: true,
  },
  {
    name: "CARTAO DE VISITAS",
    code: "5.3.6",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.3",
    isAnalytical: true,
  },
  {
    name: "FILMAKER",
    code: "5.3.7",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.3",
    isAnalytical: true,
  },
  {
    name: "AGENCIA DE TRAFEGO",
    code: "5.3.8",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.3",
    isAnalytical: true,
  },
  {
    name: "DESPESAS COM PESSOAL",
    code: "5.4",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5",
    isAnalytical: false,
  },
  {
    name: "PRO-LABORE",
    code: "5.4.1",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.4",
    isAnalytical: true,
  },
  {
    name: "FERIAS",
    code: "5.4.2",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.4",
    isAnalytical: true,
  },
  {
    name: "INSS",
    code: "5.4.3",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.4",
    isAnalytical: true,
  },
  {
    name: "FGTS",
    code: "5.4.4",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.4",
    isAnalytical: true,
  },
  {
    name: "IRRF",
    code: "5.4.5",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.4",
    isAnalytical: true,
  },
  {
    name: "SALARIO",
    code: "5.4.6",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.4",
    isAnalytical: true,
  },
  {
    name: "13 SALARIO",
    code: "5.4.7",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.4",
    isAnalytical: true,
  },
  {
    name: "DEPRECIACAO E AMORTIZACAO",
    code: "5.5",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5",
    isAnalytical: true,
  },
  {
    name: "DESPESA COM SEGUROS",
    code: "5.6",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5",
    isAnalytical: true,
  },
  {
    name: "DESPESA COM UTILIDADES",
    code: "5.7",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5",
    isAnalytical: false,
  },
  {
    name: "AGUA",
    code: "5.7.1",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.7",
    isAnalytical: true,
  },
  {
    name: "LUZ",
    code: "5.7.2",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.7",
    isAnalytical: true,
  },
  {
    name: "DESPESAS COM SISTEMAS E TI",
    code: "5.8",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5",
    isAnalytical: false,
  },
  {
    name: "OMEGA SYSTEM",
    code: "5.8.1",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.8",
    isAnalytical: true,
  },
  {
    name: "DESPESAS FINANCEIRAS",
    code: "5.9",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5",
    isAnalytical: false,
  },
  {
    name: "MULTA E JUROS",
    code: "5.9.1",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.9",
    isAnalytical: true,
  },
  {
    name: "IOF",
    code: "5.9.2",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.9",
    isAnalytical: true,
  },
  {
    name: "TARIFA PIX",
    code: "5.9.3",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.9",
    isAnalytical: true,
  },
  {
    name: "DESPESAS COM TAXAS",
    code: "5.10",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5",
    isAnalytical: false,
  },
  {
    name: "TFF/TLL",
    code: "5.10.1",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.10",
    isAnalytical: true,
  },
  {
    name: "JUCEB",
    code: "5.10.2",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.10",
    isAnalytical: true,
  },
  {
    name: "INPI",
    code: "5.10.3",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.10",
    isAnalytical: true,
  },
  {
    name: "OUTRAS DESPESAS",
    code: "5.11",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5",
    isAnalytical: false,
  },
  {
    name: "PERDA DE MERCADORIA",
    code: "5.11.1",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.11",
    isAnalytical: true,
  },
  {
    name: "CURSOS",
    code: "5.11.2",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.11",
    isAnalytical: true,
  },
  {
    name: "RETIRADA DE ESTOQUE",
    code: "5.11.3",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.11",
    isAnalytical: true,
  },
  {
    name: "IMPOSTOS",
    code: "5.12",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5",
    isAnalytical: false,
  },
  {
    name: "DAS",
    code: "5.12.1",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.12",
    isAnalytical: true,
  },
  {
    name: "PIS",
    code: "5.12.2",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.12",
    isAnalytical: true,
  },
  {
    name: "COFINS",
    code: "5.12.3",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.12",
    isAnalytical: true,
  },
  {
    name: "CSLL",
    code: "5.12.4",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.12",
    isAnalytical: true,
  },
  {
    name: "IRPJ",
    code: "5.12.5",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.12",
    isAnalytical: true,
  },
  {
    name: "ICMS",
    code: "5.12.6",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.12",
    isAnalytical: true,
  },
  {
    name: "ANTECIPACAO ICMS",
    code: "5.12.7",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.12",
    isAnalytical: true,
  },
  {
    name: "ISS",
    code: "5.12.8",
    type: "EXPENSE",
    balanceType: "DEBIT",
    parentCode: "5.12",
    isAnalytical: true,
  },
  {
    name: "CUSTOS",
    code: "6",
    type: "COST",
    balanceType: "DEBIT",
    isAnalytical: false,
  },
  {
    name: "CUSTO DA MERCADORIA VENDIDA",
    code: "6.1",
    type: "COST",
    balanceType: "DEBIT",
    parentCode: "6",
    isAnalytical: true,
  },
  {
    name: "CUSTO DO SERVICO VENDIDO",
    code: "6.2",
    type: "COST",
    balanceType: "DEBIT",
    parentCode: "6",
    isAnalytical: true,
  },
];

async function seedDefaultAccounts() {
  console.log("🟢 Iniciando seed do plano de contas...");

  for (const account of defaultAccounts.filter((a) => !a.parentCode)) {
    await db.chartOfAccounts.upsert({
      where: { code: account.code },
      update: {},
      create: {
        name: account.name,
        code: account.code,
        type: account.type as AccountType,
        balanceType: account.balanceType as BalanceType,
        isAnalytical: account.isAnalytical,
        parentCode: null,
        balance: 0,
      },
    });
  }

  for (const account of defaultAccounts.filter((a) => a.parentCode)) {
    const parentAccount = await db.chartOfAccounts.findUnique({
      where: { code: account.parentCode },
    });

    if (!parentAccount) {
      console.warn(
        `⚠️ Conta pai ${account.parentCode} não encontrada. Pulando...`,
      );
      continue;
    }

    await db.chartOfAccounts.upsert({
      where: { code: account.code },
      update: {},
      create: {
        name: account.name,
        code: account.code,
        type: account.type as AccountType,
        balanceType: account.balanceType as BalanceType,
        isAnalytical: account.isAnalytical,
        parentCode: parentAccount.code,
        balance: 0,
      },
    });
  }

  console.log("✅ Plano de contas inicial criado com sucesso.");

  console.log("🟢 Iniciando seed do Caixa...");

  const parentAccount = await db.chartOfAccounts.findUnique({
    where: { code: "1.1.1" },
  });

  if (!parentAccount) {
    console.warn(
      "Conta contábil 'Caixa e Equivalente de Caixa' não encontrada. Seed cancelado.",
    );
    return;
  }

  let cashAccount = await db.chartOfAccounts.findUnique({
    where: { code: "1.1.1.1" },
  });

  if (!cashAccount) {
    const accountCode = `${parentAccount.code}.${(await db.chartOfAccounts.count({ where: { parentCode: parentAccount.code } })) + 1}`;

    cashAccount = await db.chartOfAccounts.create({
      data: {
        name: "CAIXA",
        code: accountCode,
        type: "ASSET",
        balanceType: "DEBIT",
        isAnalytical: true,
        parentCode: parentAccount.code,
        balance: 0,
      },
    });

    console.log("✅ Conta contábil 'Caixa' criada com sucesso.");
  }

  const existingCash = await db.bank.findUnique({
    where: { name: "Caixa" },
  });

  if (!existingCash) {
    await db.bank.create({
      data: {
        name: "CAIXA",
        accountCode: cashAccount.code,
        initialBalance: 0,
        initialBalanceDate: new Date(),
        isActive: true,
        formsOfReceiving: {
          create: [{ method: "CASH" }],
        },
        formsOfPayment: {
          create: [{ method: "CASH" }],
        },
      },
    });

    console.log("✅ Caixa criado com sucesso.");
  } else {
    console.log("❌ Caixa Físico já existe, nenhum seed necessário.");
  }
}

seedDefaultAccounts()
  .catch((e) => console.error("❌ Erro ao rodar seed:", e))
  .finally(async () => {
    await db.$disconnect();
  });
